### ISSUE TITLE
Outdated github action? (failing CI)

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#193] opened 2020-12-04 11:22 UTC
@RobertRosca - does this look familiar, and can you fix it?

https://github.com/oscovida/oscovida/pull/191/checks?check_run_id=1498418949#step:2:6

**Comment by RobertRosca** [comment] 2020-12-04 11:26
Hmm odd, I've never actually seen the bot print that.

In the workflow it checks that it has the key to push to the staging repository and if it does not then it comments that message. 

As long as the branch in the PR is on the source repo it will have access to the secrets, so it shouldn't run into that issue unless the PR comes from a fork.

I'll look into this and check what the issue is.

**Comment by RobertRosca** [comment] 2020-12-07 13:53
Yeah the issue was that ssh agent action is pinned to a specific hash, and a recent deprecation broke this. The fix is included in Yury's PR #189 as well as my #195 so it will be merged along with these.

**Comment by RobertRosca** [comment] 2020-12-08 21:32
Closed by #189 merge

**Closed by RobertRosca** 2020-12-08 21:32 UTC
